services:
        
    grypho_security_bundle.authentication_failure_listener:
        class:  Grypho\SecurityBundle\Handler\AuthenticationListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - {  name: kernel.event_listener, event: security.authentication.failure,  method: onAuthenticationFailure }

    grypho_security_bundle.authentication_success_listener:
        class:  Grypho\SecurityBundle\Handler\AuthenticationListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - {  name: kernel.event_listener, event: security.interactive_login,  method: onAuthenticationSuccess }
